//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MAM.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MAMDBEntities : DbContext
    {
        public MAMDBEntities()
            : base("name=MAMDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Category> Categories { get; set; }
        public virtual DbSet<Company> Companies { get; set; }
        public virtual DbSet<DamageStock> DamageStocks { get; set; }
        public virtual DbSet<Division> Divisions { get; set; }
        public virtual DbSet<UserInfo> UserInfoes { get; set; }
        public virtual DbSet<UserRole> UserRoles { get; set; }
        public virtual DbSet<Section> Sections { get; set; }
        public virtual DbSet<StockOut> StockOuts { get; set; }
        public virtual DbSet<CSQuotation> CSQuotations { get; set; }
        public virtual DbSet<Inventory> Inventories { get; set; }
        public virtual DbSet<Supplier> Suppliers { get; set; }
        public virtual DbSet<RequisitionInfo> RequisitionInfoes { get; set; }
        public virtual DbSet<AssignedUser> AssignedUsers { get; set; }
        public virtual DbSet<PurchInvoice> PurchInvoices { get; set; }
        public virtual DbSet<PurchTable> PurchTables { get; set; }
        public virtual DbSet<Quotation> Quotations { get; set; }
    }
}
