//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MAM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PurchInvoice
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PurchInvoice()
        {
            this.PurchInvoice1 = new HashSet<PurchInvoice>();
        }
    
        public int Id { get; set; }
        public Nullable<int> PurchId { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<System.DateTime> InvDate { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PurchInvoice> PurchInvoice1 { get; set; }
        public virtual PurchInvoice PurchInvoice2 { get; set; }
    }
}
