//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MAM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RequisitionInfo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RequisitionInfo()
        {
            this.Inventories = new HashSet<Inventory>();
        }
    
        public int Id { get; set; }
        public Nullable<int> CompanyId { get; set; }
        public Nullable<int> DivisionId { get; set; }
        public Nullable<int> SectionId { get; set; }
        public Nullable<int> CategoryId { get; set; }
        public string FloorName { get; set; }
        public string ItemName { get; set; }
        public string RequisitionNo { get; set; }
        public string RequisitionPurpose { get; set; }
        public string ProductHistory { get; set; }
        public Nullable<int> ReqQty { get; set; }
        public Nullable<System.DateTime> ReqDate { get; set; }
        public byte[] QuotationImage { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> AssignedUserId { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual Company Company { get; set; }
        public virtual Division Division { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Inventory> Inventories { get; set; }
        public virtual Section Section { get; set; }
    }
}
